server:
  port: 0

spring:

  cache:
    caffeine:
      spec: expireAfterWrite=1m
    type: simple
    cache-names: weathers

  application:
    name: weather-service

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

appid: d68292891fafb2a9ce37d00a676075cb


url:
  weather: https://api.openweathermap.org/data/2.5/weather

