server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

logging:
  level:
    root: INFO
    com.netflix: trace # Уровень логирования для пакетов Zuul
  file:
    name: logs/app.log # Имя файла логов
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" # Шаблон вывода в консоль
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n" # Шаблон вывода в файл