server:
  port: 0

spring:
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: location-service
  datasource:
    url: jdbc:h2:file:./data/demo



eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
